name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    
    # Gradle wrapper 파일 실행 권한주기
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew    

    
    # Gradle test를 실행한다
    - name: Test with Gradle
      run: ./gradlew --info test

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()  # 테스트가 실패하여도 Report를 보기 위해 `always`로 설정
      with:
        files: |
          build/test-results/**/*.xml
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

#      # 추가
#      - name: Make zip file #1
#        run: zip -qq -r ./$GITHUB_SHA.zip .
#        shell: bash
#
#      - name: Configure AWS credentials #2
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
#          aws-region: ap-northeast-2
#
#      - name: Upload to S3 #3
#        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ secrets.S3_BUCKET_NAME }}/$GITHUB_SHA.zip
#
#      - name: Code Deploy #4
#        run: aws deploy create-deployment --application-name gk-todo
#          --deployment-config-name CodeDeployDefault.OneAtATime
#          --deployment-group-name dev
#          --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=$GITHUB_SHA.zip
